# ============================================
# Ansible Inventory - Smart City Portal
# ============================================
# Replace <BLUE_IP> and <GREEN_IP> with actual IPs
# from 'terraform output' after running terraform apply

[blue]
blue-server ansible_host={{ blue_ip }} ansible_user=ec2-user

[green]
green-server ansible_host={{ green_ip }} ansible_user=ec2-user

[webservers:children]
blue
green

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
