# ============================================
# Ansible Inventory - Smart City Portal
# ============================================
# Replace <BLUE_IP> and <GREEN_IP> with actual IPs
# from 'terraform output' after running terraform apply

[blue]
blue-server ansible_host=<BLUE_IP> ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/smart-city-key.pem

[green]
green-server ansible_host=<GREEN_IP> ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/smart-city-key.pem

[webservers:children]
blue
green

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
